jobs:
  build:
    if: github.repository == 'apache/camel'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - continue-on-error: true
      name: Set up JDK ${{ matrix.os }}
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: mvn build ${{ matrix.os }}
      run: ./mvnw -B -V -D'http.keepAlive=false' -l build.log -D'maven.wagon.http.pool=false'
        -D'maven.wagon.httpconnectionManager.ttlSeconds=120' --no-transfer-progress
        -Dquickly install
    - continue-on-error: true
      if: always()
      name: Archive logs ${{ matrix.os }}
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ matrix.os }}
        path: build.log
        retention-days: 2
    strategy:
      fail-fast: false
      matrix:
        os:
        - windows-latest
        - macos-latest
        - windows-2019
name: Alternative OS Build (Camel 4)
on:
  repository_dispatch:
    types: trigger-ga___alternative-os-build-main.yml
permissions:
  contents: read
