jobs:
  process:
    if: github.repository == 'apache/camel'
    name: Process
    permissions:
      contents: read
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: "github.event_name == 'pull_request_target' &&\n  (github.event.action ==\
        \ 'opened' ||\n   github.event.action == 'reopened' ||\n   github.event.action\
        \ == 'synchronize')\n"
      name: Label changes scope
      uses: actions/labeler@v5.0.0
      with:
        configuration-path: .github/workflows/generic-pr/label-config.yml
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        sync-labels: true
name: label pr
on:
  repository_dispatch:
    types: trigger-ga___generic-pr.yaml
permissions:
  contents: read
