jobs:
  build:
    if: github.repository == 'apache/camel'
    permissions:
      contents: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - continue-on-error: true
      id: install-mvnd
      uses: ./.github/actions/install-mvnd
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: mvn build and sbom generation
      run: ./mvnw -B -l build.log -Psbom -Dquickly verify
    - continue-on-error: true
      if: always()
      name: archive logs
      uses: actions/upload-artifact@v4
      with:
        name: build.log
        path: build.log
    - continue-on-error: true
      name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        assignees: oscerd
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        base: main
        body: 'Regen bot :robot: found some uncommitted changes after running build
          on :camel: `main` branch for generating SBOMs.

          Please do not delete `regen_bot_sbom` branch after merge/rebase.

          '
        branch: regen_bot_sbom
        commit-message: Regen SBOM from commit ${{ github.sha }}
        committer: GitHub <noreply@github.com>
        labels: 'regen

          automated pr

          camel-4

          '
        signoff: true
        title: Generated sources regen for SBOM
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        java:
        - '17'
name: Generate SBOM (Camel 4)
on:
  repository_dispatch:
    types: trigger-ga___generate-sbom-main.yml
permissions: {}
