jobs:
  build:
    if: github.repository == 'apache/camel'
    permissions:
      issues: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - continue-on-error: true
      id: install-packages
      uses: ./.github/actions/install-packages
    - continue-on-error: true
      id: install-mvnd
      uses: ./.github/actions/install-mvnd
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: maven build
      run: ./mvnw -l build.log -Dquickly install
    - continue-on-error: true
      if: always()
      name: archive logs
      uses: actions/upload-artifact@v4
      with:
        name: build.log
        path: build.log
    - continue-on-error: true
      name: Fail if there are uncommitted changes
      run: '[[ -z $(git status --porcelain) ]] || { echo ''There are uncommitted changes'';
        git status; echo; echo; git diff; exit 1; }

        '
      shell: bash
    - continue-on-error: true
      name: mvn test
      uses: ./.github/actions/incremental-build
      with:
        artifact-upload-suffix: java-${{ matrix.java }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        mode: test
        pr-id: ${{ github.event.number }}
        skip-mvnd-install: 'true'
    strategy:
      matrix:
        java:
        - '17'
name: PR Build (Camel 4)
on:
  repository_dispatch:
    types: trigger-ga___pr-build-camel-40x.yml
