jobs:
  pr_commented:
    if: ${{ github.repository == 'apache/camel' && github.event.issue.pull_request
      && (github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association
      == 'OWNER' || github.event.comment.author_association == 'CONTRIBUTOR') && startsWith(github.event.comment.body,
      '/component-test') }}
    name: PR comment
    permissions:
      actions: read
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Retrieve sha
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: "const pr = await github.rest.pulls.get({\n      owner: context.repo.owner,\n\
          \      repo: context.repo.repo,\n      pull_number: context.issue.number\n\
          });\ncore.exportVariable('pr_sha', pr.data.head.sha)\n"
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        ref: ${{ env.pr_sha }}
        submodules: recursive
    - continue-on-error: true
      uses: ./.github/actions/create-or-update-comment
      with:
        body: ':robot: The Apache Camel test robot will run the tests for you :+1:

          '
        issue-number: ${{ github.event.issue.number }}
    - continue-on-error: true
      id: install-packages
      uses: ./.github/actions/install-packages
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      id: test
      name: Component test execution
      uses: ./.github/actions/component-test
      with:
        artifact-upload-suffix: java-${{ matrix.java }}
        comment-body: ${{ github.event.comment.body }}
        comment-id: ${{ github.event.comment.id }}
        pr-id: ${{ github.event.issue.number }}
        run-id: ${{ github.run_id }}
    strategy:
      matrix:
        java:
        - '17'
name: PR Comment Build
on:
  repository_dispatch:
    types: trigger-ga___pr-comment.yml
